# Generated by Django 6.0.1 on 2026-02-01 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_total_amount'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cartitem',
            name='orders_cart_user_id_154617_idx',
        ),
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_item',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_user_id_0886b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orders_orde_order_i_52f79a_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
