# Generated by Django 6.0.1 on 2026-01-27 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (KES)')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Stock Quantity')),
                ('harvest_date', models.DateField(verbose_name='Harvest Date')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('weight_per_unit', models.CharField(default='kg', max_length=20, verbose_name='Weight Unit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Category')),
                ('farmer', models.ForeignKey(limit_choices_to={'user_type': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Farmer')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'is_available'], name='idx_category_available'), models.Index(fields=['price'], name='idx_price'), models.Index(fields=['harvest_date'], name='idx_harvest_date'), models.Index(fields=['farmer'], name='idx_farmer')],
            },
        ),
    ]
